/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as legasiLpSol from "./LegasiLP.sol";
export type { legasiLpSol };
export type { LegasiCore } from "./LegasiCore";
export type { LegasiGAD } from "./LegasiGAD";
export type { LegasiLending } from "./LegasiLending";
export type { ReputationRegistry } from "./ReputationRegistry";
export type { X402Receipt } from "./X402Receipt";
