/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LegasiCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "borrowableConfigs"
      | "collateralConfigs"
      | "owner"
      | "priceFeeds"
      | "protocol"
      | "registerBorrowable"
      | "registerCollateral"
      | "renounceOwnership"
      | "setPaused"
      | "transferOwnership"
      | "updatePrice"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BorrowableRegistered"
      | "CollateralRegistered"
      | "OwnershipTransferred"
      | "Paused"
      | "PriceUpdated"
      | "ProtocolInitialized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "borrowableConfigs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralConfigs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceFeeds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "protocol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerBorrowable",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCollateral",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrice",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "borrowableConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceFeeds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerBorrowable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrice",
    data: BytesLike
  ): Result;
}

export namespace BorrowableRegisteredEvent {
  export type InputTuple = [token: AddressLike, rateBps: BigNumberish];
  export type OutputTuple = [token: string, rateBps: bigint];
  export interface OutputObject {
    token: string;
    rateBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralRegisteredEvent {
  export type InputTuple = [token: AddressLike, maxLtvBps: BigNumberish];
  export type OutputTuple = [token: string, maxLtvBps: bigint];
  export interface OutputObject {
    token: string;
    maxLtvBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    token: AddressLike,
    priceUsd6: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    priceUsd6: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    token: string;
    priceUsd6: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolInitializedEvent {
  export type InputTuple = [admin: AddressLike, treasury: AddressLike];
  export type OutputTuple = [admin: string, treasury: string];
  export interface OutputObject {
    admin: string;
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LegasiCore extends BaseContract {
  connect(runner?: ContractRunner | null): LegasiCore;
  waitForDeployment(): Promise<this>;

  interface: LegasiCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  borrowableConfigs: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint] & {
        isActive: boolean;
        interestRateBps: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;

  collateralConfigs: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        isActive: boolean;
        maxLtvBps: bigint;
        liquidationThresholdBps: bigint;
        liquidationBonusBps: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  priceFeeds: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { priceUsd6: bigint; lastUpdate: bigint }],
    "view"
  >;

  protocol: TypedContractMethod<
    [],
    [[string, boolean] & { treasury: string; paused: boolean }],
    "view"
  >;

  registerBorrowable: TypedContractMethod<
    [token: AddressLike, interestRateBps: BigNumberish, decimals: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerCollateral: TypedContractMethod<
    [
      token: AddressLike,
      maxLtvBps: BigNumberish,
      liquidationThresholdBps: BigNumberish,
      liquidationBonusBps: BigNumberish,
      decimals: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPaused: TypedContractMethod<[_paused: boolean], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePrice: TypedContractMethod<
    [token: AddressLike, priceUsd6: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "borrowableConfigs"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint] & {
        isActive: boolean;
        interestRateBps: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "collateralConfigs"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        isActive: boolean;
        maxLtvBps: bigint;
        liquidationThresholdBps: bigint;
        liquidationBonusBps: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceFeeds"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { priceUsd6: bigint; lastUpdate: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocol"
  ): TypedContractMethod<
    [],
    [[string, boolean] & { treasury: string; paused: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerBorrowable"
  ): TypedContractMethod<
    [token: AddressLike, interestRateBps: BigNumberish, decimals: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerCollateral"
  ): TypedContractMethod<
    [
      token: AddressLike,
      maxLtvBps: BigNumberish,
      liquidationThresholdBps: BigNumberish,
      liquidationBonusBps: BigNumberish,
      decimals: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePrice"
  ): TypedContractMethod<
    [token: AddressLike, priceUsd6: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BorrowableRegistered"
  ): TypedContractEvent<
    BorrowableRegisteredEvent.InputTuple,
    BorrowableRegisteredEvent.OutputTuple,
    BorrowableRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CollateralRegistered"
  ): TypedContractEvent<
    CollateralRegisteredEvent.InputTuple,
    CollateralRegisteredEvent.OutputTuple,
    CollateralRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolInitialized"
  ): TypedContractEvent<
    ProtocolInitializedEvent.InputTuple,
    ProtocolInitializedEvent.OutputTuple,
    ProtocolInitializedEvent.OutputObject
  >;

  filters: {
    "BorrowableRegistered(address,uint16)": TypedContractEvent<
      BorrowableRegisteredEvent.InputTuple,
      BorrowableRegisteredEvent.OutputTuple,
      BorrowableRegisteredEvent.OutputObject
    >;
    BorrowableRegistered: TypedContractEvent<
      BorrowableRegisteredEvent.InputTuple,
      BorrowableRegisteredEvent.OutputTuple,
      BorrowableRegisteredEvent.OutputObject
    >;

    "CollateralRegistered(address,uint16)": TypedContractEvent<
      CollateralRegisteredEvent.InputTuple,
      CollateralRegisteredEvent.OutputTuple,
      CollateralRegisteredEvent.OutputObject
    >;
    CollateralRegistered: TypedContractEvent<
      CollateralRegisteredEvent.InputTuple,
      CollateralRegisteredEvent.OutputTuple,
      CollateralRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(bool)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PriceUpdated(address,uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "ProtocolInitialized(address,address)": TypedContractEvent<
      ProtocolInitializedEvent.InputTuple,
      ProtocolInitializedEvent.OutputTuple,
      ProtocolInitializedEvent.OutputObject
    >;
    ProtocolInitialized: TypedContractEvent<
      ProtocolInitializedEvent.InputTuple,
      ProtocolInitializedEvent.OutputTuple,
      ProtocolInitializedEvent.OutputObject
    >;
  };
}
