/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LegasiGADInterface extends Interface {
  getFunction(
    nameOrSignature: "configureGad" | "crank" | "gadConfigs"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GadConfigured" | "GadCranked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "configureGad",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "crank", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gadConfigs",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "configureGad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "crank", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gadConfigs", data: BytesLike): Result;
}

export namespace GadConfiguredEvent {
  export type InputTuple = [
    user: AddressLike,
    startThresholdBps: BigNumberish,
    stepBps: BigNumberish,
    minInterval: BigNumberish,
    enabled: boolean
  ];
  export type OutputTuple = [
    user: string,
    startThresholdBps: bigint,
    stepBps: bigint,
    minInterval: bigint,
    enabled: boolean
  ];
  export interface OutputObject {
    user: string;
    startThresholdBps: bigint;
    stepBps: bigint;
    minInterval: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GadCrankedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LegasiGAD extends BaseContract {
  connect(runner?: ContractRunner | null): LegasiGAD;
  waitForDeployment(): Promise<this>;

  interface: LegasiGADInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  configureGad: TypedContractMethod<
    [
      startThresholdBps: BigNumberish,
      stepBps: BigNumberish,
      minInterval: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;

  crank: TypedContractMethod<[], [void], "nonpayable">;

  gadConfigs: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        startThresholdBps: bigint;
        stepBps: bigint;
        minInterval: bigint;
        lastCrank: bigint;
        enabled: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "configureGad"
  ): TypedContractMethod<
    [
      startThresholdBps: BigNumberish,
      stepBps: BigNumberish,
      minInterval: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "crank"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gadConfigs"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        startThresholdBps: bigint;
        stepBps: bigint;
        minInterval: bigint;
        lastCrank: bigint;
        enabled: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "GadConfigured"
  ): TypedContractEvent<
    GadConfiguredEvent.InputTuple,
    GadConfiguredEvent.OutputTuple,
    GadConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "GadCranked"
  ): TypedContractEvent<
    GadCrankedEvent.InputTuple,
    GadCrankedEvent.OutputTuple,
    GadCrankedEvent.OutputObject
  >;

  filters: {
    "GadConfigured(address,uint16,uint16,uint256,bool)": TypedContractEvent<
      GadConfiguredEvent.InputTuple,
      GadConfiguredEvent.OutputTuple,
      GadConfiguredEvent.OutputObject
    >;
    GadConfigured: TypedContractEvent<
      GadConfiguredEvent.InputTuple,
      GadConfiguredEvent.OutputTuple,
      GadConfiguredEvent.OutputObject
    >;

    "GadCranked(address,uint256)": TypedContractEvent<
      GadCrankedEvent.InputTuple,
      GadCrankedEvent.OutputTuple,
      GadCrankedEvent.OutputObject
    >;
    GadCranked: TypedContractEvent<
      GadCrankedEvent.InputTuple,
      GadCrankedEvent.OutputTuple,
      GadCrankedEvent.OutputObject
    >;
  };
}
