/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReputationRegistry {
  export type ReputationStruct = {
    score: BigNumberish;
    successfulRepayments: BigNumberish;
    totalRepaidUsd6: BigNumberish;
    gadEvents: BigNumberish;
    lastUpdate: BigNumberish;
  };

  export type ReputationStructOutput = [
    score: bigint,
    successfulRepayments: bigint,
    totalRepaidUsd6: bigint,
    gadEvents: bigint,
    lastUpdate: bigint
  ] & {
    score: bigint;
    successfulRepayments: bigint;
    totalRepaidUsd6: bigint;
    gadEvents: bigint;
    lastUpdate: bigint;
  };
}

export interface ReputationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getReputation"
      | "reputations"
      | "updateOnGad"
      | "updateOnRepay"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ReputationUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reputations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOnGad",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOnRepay",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOnGad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOnRepay",
    data: BytesLike
  ): Result;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    score: BigNumberish,
    totalRepaidUsd6: BigNumberish,
    gadEvents: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    score: bigint,
    totalRepaidUsd6: bigint,
    gadEvents: bigint
  ];
  export interface OutputObject {
    agent: string;
    score: bigint;
    totalRepaidUsd6: bigint;
    gadEvents: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReputationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getReputation: TypedContractMethod<
    [agent: AddressLike],
    [ReputationRegistry.ReputationStructOutput],
    "view"
  >;

  reputations: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        score: bigint;
        successfulRepayments: bigint;
        totalRepaidUsd6: bigint;
        gadEvents: bigint;
        lastUpdate: bigint;
      }
    ],
    "view"
  >;

  updateOnGad: TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;

  updateOnRepay: TypedContractMethod<
    [agent: AddressLike, repaidUsd6: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<
    [agent: AddressLike],
    [ReputationRegistry.ReputationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "reputations"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        score: bigint;
        successfulRepayments: bigint;
        totalRepaidUsd6: bigint;
        gadEvents: bigint;
        lastUpdate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateOnGad"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateOnRepay"
  ): TypedContractMethod<
    [agent: AddressLike, repaidUsd6: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;

  filters: {
    "ReputationUpdated(address,uint256,uint256,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
  };
}
