/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface X402ReceiptInterface extends Interface {
  getFunction(nameOrSignature: "receipts" | "record"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "X402Paid"): EventFragment;

  encodeFunctionData(functionFragment: "receipts", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "record",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "receipts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "record", data: BytesLike): Result;
}

export namespace X402PaidEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    payer: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    payer: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    payer: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface X402Receipt extends BaseContract {
  connect(runner?: ContractRunner | null): X402Receipt;
  waitForDeployment(): Promise<this>;

  interface: X402ReceiptInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  receipts: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint] & {
        paymentId: string;
        payer: string;
        recipient: string;
        amount: bigint;
        paidAt: bigint;
      }
    ],
    "view"
  >;

  record: TypedContractMethod<
    [
      paymentId: BytesLike,
      payer: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "receipts"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint] & {
        paymentId: string;
        payer: string;
        recipient: string;
        amount: bigint;
        paidAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "record"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      payer: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "X402Paid"
  ): TypedContractEvent<
    X402PaidEvent.InputTuple,
    X402PaidEvent.OutputTuple,
    X402PaidEvent.OutputObject
  >;

  filters: {
    "X402Paid(bytes32,address,address,uint256)": TypedContractEvent<
      X402PaidEvent.InputTuple,
      X402PaidEvent.OutputTuple,
      X402PaidEvent.OutputObject
    >;
    X402Paid: TypedContractEvent<
      X402PaidEvent.InputTuple,
      X402PaidEvent.OutputTuple,
      X402PaidEvent.OutputObject
    >;
  };
}
