/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LegasiLP__factory } from "./LegasiLP__factory";
export { LpToken__factory } from "./LpToken__factory";
