/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FlashLoanArbitrage } from "./FlashLoanArbitrage";
export type { IFlashLoanReceiver } from "./IFlashLoanReceiver";
export type { LegasiFlash } from "./LegasiFlash";
