/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { LegasiGAD, LegasiGADInterface } from "../../contracts/LegasiGAD";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "startThresholdBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "stepBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "minInterval",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
    ],
    name: "GadConfigured",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "GadCranked",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "startThresholdBps",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "stepBps",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "minInterval",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
    ],
    name: "configureGad",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "crank",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "gadConfigs",
    outputs: [
      {
        internalType: "uint16",
        name: "startThresholdBps",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "stepBps",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "minInterval",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastCrank",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061038d806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80633bab6414146100465780639c16a9e8146100bf578063bdbb9f97146100c9575b600080fd5b61008b610054366004610295565b600060208190529081526040902080546001820154600283015460039093015461ffff808416946201000090940416929060ff1685565b6040805161ffff96871681529590941660208601529284019190915260608301521515608082015260a00160405180910390f35b6100c76100dc565b005b6100c76100d73660046102dc565b6101bd565b336000908152602081905260409020600381015460ff1661012f5760405162461bcd60e51b8152602060048201526008602482015267191a5cd8589b195960c21b60448201526064015b60405180910390fd5b806001015481600201546101439190610330565b42101561017d5760405162461bcd60e51b815260206004820152600860248201526731b7b7b63237bbb760c11b6044820152606401610126565b426002820181905560405190815233907fb2aafc133483fbd6466f156a466497f4cc2cfbaaf1a86420f5b50e304cb87df89060200160405180910390a250565b6040805160a08101825261ffff8681168083528682166020808501828152858701898152600060608089018281528b15156080808c0182815233808752868a52958e90209c518d5498518d16620100000263ffffffff199099169c169b909b17969096178b55935160018b01555160028a015596516003909801805498151560ff19909916989098179097558751948552918401929092529482018790529181019390935290917f8debc6eccc51a33ca8751c600df767954dfef373e566ab2e22219c48cf01b7fa910160405180910390a250505050565b6000602082840312156102a757600080fd5b81356001600160a01b03811681146102be57600080fd5b9392505050565b803561ffff811681146102d757600080fd5b919050565b600080600080608085870312156102f257600080fd5b6102fb856102c5565b9350610309602086016102c5565b9250604085013591506060850135801515811461032557600080fd5b939692955090935050565b8082018082111561035157634e487b7160e01b600052601160045260246000fd5b9291505056fea2646970667358221220fa417e0fbcdfc04c1c988ee2d3fefda29db931baa552b773fb02b5856dc09f3264736f6c63430008140033";

type LegasiGADConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LegasiGADConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LegasiGAD__factory extends ContractFactory {
  constructor(...args: LegasiGADConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      LegasiGAD & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): LegasiGAD__factory {
    return super.connect(runner) as LegasiGAD__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LegasiGADInterface {
    return new Interface(_abi) as LegasiGADInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): LegasiGAD {
    return new Contract(address, _abi, runner) as unknown as LegasiGAD;
  }
}
