/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  X402Receipt,
  X402ReceiptInterface,
} from "../../contracts/X402Receipt";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "X402Paid",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "receipts",
    outputs: [
      {
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "paidAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "record",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234610016576101eb908161001c8239f35b600080fdfe608060408181526004908136101561001657600080fd5b600092833560e01c908163981a0af514610097575063ef6cf04d1461003a57600080fd5b34610093576020366003190112610093578060a093833581528060205220805492600180861b03928360018401541693600284015416916003840154930154938151958652602086015284015260608301526080820152f35b8280fd5b9050839134610093576080366003190112610093578335916001600160a01b0391602435838116908190036101b157604435928484168094036101ad576064359460a0820182811067ffffffffffffffff82111761019a579189897ff9edb41aea050c6e881aecc88630fc6ba05dbd41348c1de2726e5e60420e535699979593879560809a9852888452602084018581528685019088825260608601928a8452888d8801954287528d81528060205220965187558060018801925116916bffffffffffffffffffffffff60a01b9283825416179055600287019251169082541617905551600384015551910155815194855260208501528301526060820152a180f35b634e487b7160e01b895260418a52602489fd5b8680fd5b8580fdfea2646970667358221220782440e848f92ef671109a70d68e9681b443e5172b5c989a2ea7fe5bae94300d64736f6c63430008140033";

type X402ReceiptConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: X402ReceiptConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class X402Receipt__factory extends ContractFactory {
  constructor(...args: X402ReceiptConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      X402Receipt & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): X402Receipt__factory {
    return super.connect(runner) as X402Receipt__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): X402ReceiptInterface {
    return new Interface(_abi) as X402ReceiptInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): X402Receipt {
    return new Contract(address, _abi, runner) as unknown as X402Receipt;
  }
}
