/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  X402Receipt,
  X402ReceiptInterface,
} from "../../contracts/X402Receipt";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "X402Paid",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "receipts",
    outputs: [
      {
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "paidAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "record",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610264806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063981a0af51461003b578063ef6cf04d14610050575b600080fd5b61004e6100493660046101d1565b6100d1565b005b61009961005e366004610215565b6000602081905290815260409020805460018201546002830154600384015460049094015492936001600160a01b0392831693929091169185565b604080519586526001600160a01b03948516602087015292909316918401919091526060830152608082015260a00160405180910390f35b6040805160a0810182528581526001600160a01b03808616602080840191825286831684860190815260608501878152426080870190815260008c815293849052928790209551865592516001860180549186166001600160a01b031992831617905590516002860180549190951691161790925551600383015551600490910155517ff9edb41aea050c6e881aecc88630fc6ba05dbd41348c1de2726e5e60420e5356906101a79086908690869086909384526001600160a01b03928316602085015291166040830152606082015260800190565b60405180910390a150505050565b80356001600160a01b03811681146101cc57600080fd5b919050565b600080600080608085870312156101e757600080fd5b843593506101f7602086016101b5565b9250610205604086016101b5565b9396929550929360600135925050565b60006020828403121561022757600080fd5b503591905056fea26469706673582212208b69e285f32a8cc825c918feda2666ce42eb1cc7fe0e29cf270a67dcbc59d0aa64736f6c63430008140033";

type X402ReceiptConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: X402ReceiptConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class X402Receipt__factory extends ContractFactory {
  constructor(...args: X402ReceiptConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      X402Receipt & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): X402Receipt__factory {
    return super.connect(runner) as X402Receipt__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): X402ReceiptInterface {
    return new Interface(_abi) as X402ReceiptInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): X402Receipt {
    return new Contract(address, _abi, runner) as unknown as X402Receipt;
  }
}
