/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  FlashLoanArbitrage,
  FlashLoanArbitrageInterface,
} from "../../../contracts/LegasiFlash.sol/FlashLoanArbitrage";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "initiator",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onFlashLoan",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234610016576102e4908161001c8239f35b600080fdfe608060405260048036101561001357600080fd5b600090813560e01c6323e30c8b1461002a57600080fd5b346102025760a0366003190112610202576001600160a01b03813581811681036101ca5760248035928316938484036101fe576044356084359567ffffffffffffffff968781116101fa57366023820112156101fa57808401358881116101f6578101858101903682116101f2578260809103126101f6576100ad868301610206565b506100ba60448301610206565b5060648201358981116101f25781876100d592850101610257565b506084820135918983116101f2576100ef92018601610257565b506064358201908183116101e05790889392916040519163095ea7b360e01b83523385840152868301528160448160209c8d945af180156101d55761019a575b5060405194888601966bffffffffffffffffffffffff19809260601b16885260601b16603486015260488501524260688501524360888501526088845260c08401958487109087111761018a57505050826040525190208152f35b634e487b7160e01b825260419052fd5b8881813d83116101ce575b6101af818361021f565b810103126101ca5751801515036101c6573861012f565b8280fd5b8380fd5b503d6101a5565b6040513d86823e3d90fd5b634e487b7160e01b8952601184528489fd5b8a80fd5b8980fd5b8880fd5b8580fd5b5080fd5b35906001600160a01b038216820361021a57565b600080fd5b90601f8019910116810190811067ffffffffffffffff82111761024157604052565b634e487b7160e01b600052604160045260246000fd5b81601f8201121561021a5780359067ffffffffffffffff8211610241576040519261028c601f8401601f19166020018561021f565b8284526020838301011161021a5781600092602080930183860137830101529056fea2646970667358221220d0a07e2c87f195cf21da30b326a73770a16b1eb02b461a788feaabc6215ca67e64736f6c63430008140033";

type FlashLoanArbitrageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FlashLoanArbitrageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FlashLoanArbitrage__factory extends ContractFactory {
  constructor(...args: FlashLoanArbitrageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      FlashLoanArbitrage & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): FlashLoanArbitrage__factory {
    return super.connect(runner) as FlashLoanArbitrage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FlashLoanArbitrageInterface {
    return new Interface(_abi) as FlashLoanArbitrageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FlashLoanArbitrage {
    return new Contract(address, _abi, runner) as unknown as FlashLoanArbitrage;
  }
}
