/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "LegasiCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegasiCore__factory>;
    getContractFactory(
      name: "LegasiGAD",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegasiGAD__factory>;
    getContractFactory(
      name: "LegasiLending",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegasiLending__factory>;
    getContractFactory(
      name: "LegasiLP",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegasiLP__factory>;
    getContractFactory(
      name: "LpToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LpToken__factory>;
    getContractFactory(
      name: "ReputationRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReputationRegistry__factory>;
    getContractFactory(
      name: "X402Receipt",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.X402Receipt__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "LegasiCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LegasiCore>;
    getContractAt(
      name: "LegasiGAD",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LegasiGAD>;
    getContractAt(
      name: "LegasiLending",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LegasiLending>;
    getContractAt(
      name: "LegasiLP",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LegasiLP>;
    getContractAt(
      name: "LpToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LpToken>;
    getContractAt(
      name: "ReputationRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReputationRegistry>;
    getContractAt(
      name: "X402Receipt",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.X402Receipt>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "LegasiCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegasiCore>;
    deployContract(
      name: "LegasiGAD",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegasiGAD>;
    deployContract(
      name: "LegasiLending",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegasiLending>;
    deployContract(
      name: "LegasiLP",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegasiLP>;
    deployContract(
      name: "LpToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LpToken>;
    deployContract(
      name: "ReputationRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReputationRegistry>;
    deployContract(
      name: "X402Receipt",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.X402Receipt>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "LegasiCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegasiCore>;
    deployContract(
      name: "LegasiGAD",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegasiGAD>;
    deployContract(
      name: "LegasiLending",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegasiLending>;
    deployContract(
      name: "LegasiLP",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegasiLP>;
    deployContract(
      name: "LpToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LpToken>;
    deployContract(
      name: "ReputationRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReputationRegistry>;
    deployContract(
      name: "X402Receipt",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.X402Receipt>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
